version: "3"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    ports:
      - '55432:5432'
  webapp:
    build: .
    restart: always
    links:
      - 'postgres:postgres'
      - 'minio:minio'
    ports:
      - '56481:443'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/
  minio:
    image: bitnami/minio:latest
    restart: always
    hostname: minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9009:9009"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - SPRING_DATASOURCE_URL=http://minio:9009
    command: server /data --console-address ":9009"
    volumes:
      - /srv/minio:/bitnami/minio/data

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450