version: "3"
services:
  postgres:
    image: postgres:14.1-alpine
    restart: always
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
  minio:
    image: bitnami/minio:latest
    restart: always
    hostname: minio
    expose:
      - 9009
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_DEFAULT_BUCKET=main
    command: minio server --address :9009 /bitnami/minio/data
  webapp:
    build: .
    restart: always
    links:
      - postgres:postgres
      - minio:minio
    ports:
      - '56481:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/
      - MINIO_URL=http://minio:9009
      - ALLOWED_ORIGIN=http://172.22.0.20:56481

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450