server:
  http_listen_port: 9080
  grpc_listen_port: 0

clients:
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/positions.yaml

client:
  backoff_config:
    max_period: 1m

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: [__meta_docker_container_label_promtail]
        regex: true
        action: keep
      - source_labels: [__meta_docker_container_logpath]
        target_label: __path__
      - source_labels: [__meta_docker_container_name]
        target_label: container
      - source_labels: [__meta_docker_container_image]
        target_label: image
  - job_name: webapp-logfile
    static_configs:
      - targets:
          - localhost
        labels:
          job: webapp-logfile
          __path__: /webapp-logs/app-json*.log
          container: webapp