server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  backoff_config:
    max_period: 1m

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: json-log
    static_configs:
      - targets:
          - localhost
        labels:
          job: itdesk-webapp
          __path__: /var/log/app-json.log
    pipeline_stages:
      - docker: {}
    relabel_configs:
      - source_labels: [__path__]
        regex: '/var/lib/docker/containers/([^/]+)/.*'
        target_label: container_id
      - source_labels: [__path__]
        regex: '.*/([a-zA-Z0-9_.-]+)-json.log'
        target_label: container_name
      - source_labels: [container_name]
        regex: 'itdesk-webapp-1'
        target_label: app
        replacement: itdesk