common:
  path_prefix: /loki

schema_config:
  configs:
    - from: 2022-01-01
      store: boltdb-shipper
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /data/index
    cache_location: /data/cache
    shared_store: filesystem
  filesystem:
    directory: /data/chunks

compactor:
  working_directory: /data/compactor