server:
  port: 8080
  servlet.session.timeout: 4320
  tomcat.max-swallow-size: 512MB

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  session:
    jdbc:
      flush-mode: on_save
      table-name: SPRING_SESSION
      initialize-schema: always
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 512MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false
  jackson:
    serialization:
      write-dates-as-timestamps: false

minio:
  url: ${MINIO_URL}
  accessKey: minioadmin
  secretKey: minioadmin
  bucket-name: ${MINIO_DEFAULT_BUCKET}

management:
  server.port: 8081
  endpoints.web.exposure.include: health,info,metrics,unistat,sessions,loggers,env
  endpoint.health.show-details: always
  security:
    enabled: false
    role: ADMIN

allowed-origin: ${ALLOWED_ORIGIN}
instance-name: ${INSTANCE_NAME}
license-server-url: https://admin.uldesk.ru

logging:
  level:
    org.flywaydb: INFO
    org.hibernate:
      SQL: INFO
    org.springframework:
      web.SimpLogging: INFO
      boot.autoconfigure: INFO
    org.springframework.web.servlet:
      DispatcherServlet: INFO
    org.springframework.web.servlet.handler:
      SimpleUrlHandlerMapping: INFO
    org.springframework.web.socket.config:
      WebSocketMessageBrokerStats: INFO
    org.springframework.web.servlet.mvc.method.annotation:
      HttpEntityMethodProcessor: INFO
      RequestMappingHandlerMapping: INFO
    org.springframework.web.socket.messaging:
      WebSocketAnnotationMethodMessageHandler: INFO
    org.springframework.jdbc.core:
      JdbcTemplate: INFO