server:
  port: 8080
  servlet.session.timeout: 4320
  
spring:
  datasource.url: ${SPRING_DATASOURCE_URL}
  datasource.username: postgres
  datasource.password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

logging:
  level:
    org.hibernate:
      SQL: WARN
    org.springframework:
      web.SimpLogging: WARN
      boot.autoconfigure: WARN
    org.springframework.web.servlet:
      DispatcherServlet: WARN
    org.springframework.web.servlet.handler:
      SimpleUrlHandlerMapping: WARN
    org.springframework.web.socket.config:
      WebSocketMessageBrokerStats: WARN