server:
  port: 8080
  servlet.session.timeout: 4320
  
spring:
  datasource.url: jdbc:postgresql://localhost:5432/it_desk
  datasource.username: postgres
  datasource.password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

logging:
  level:
    org.hibernate.SQL: WARN
    org.springframework.web.SimpLogging: WARN