server:
  port: 8080
  servlet.session.timeout: 4320
  
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    baseline-version: 0
  session:
    jdbc:
      flush-mode: on_save
      table-name: SPRING_SESSION
      initialize-schema: always
#  sql:
#    init:
#      mode: always
#      schema-locations: classpath:org/springframework/session/jdbc/schema-postgresql.sql

logging:
  level:
    org.flywaydb: INFO
    org.hibernate:
      SQL: INFO
    org.springframework:
      web.SimpLogging: INFO
      boot.autoconfigure: INFO
    org.springframework.web.servlet:
      DispatcherServlet: INFO
    org.springframework.web.servlet.handler:
      SimpleUrlHandlerMapping: INFO
    org.springframework.web.socket.config:
      WebSocketMessageBrokerStats: INFO
    org.springframework.web.servlet.mvc.method.annotation:
      HttpEntityMethodProcessor: INFO
      RequestMappingHandlerMapping: INFO
    org.springframework.web.socket.messaging:
      WebSocketAnnotationMethodMessageHandler: INFO
    org.springframework.jdbc.core:
      JdbcTemplate: INFO