package ru.ravel.ItDesk.model.automatosation;

public enum SkipReason {
	CONDITIONS_NOT_MET,
	RULE_DISABLED,
	COOLDOWN_ACTIVE,
	DUPLICATE_EVENT,
	LOOP_GUARD_TRIGGERED,
	PERMISSION_DENIED,

	EVENT_ALREADY_PROCESSED,
	ENTITY_NOT_FOUND,
	ACTION_NOT_FOUND,
	FUNCTION_NOT_FOUND,
	INVALID_EXPRESSION,
	INVALID_ACTION,
	INVALID_PAYLOAD,
	RATE_LIMITED,
	RETRY_LIMIT_REACHED,
	TIMEOUT,
	SYSTEM_ERROR,
	MANUAL_SKIP,
	;
}