package ru.ravel.ItDesk.model;

public enum UserNotificationEvent {
	MENTIONED_USER,
	MENTIONED_USER_IN_TASK_CHAT,
	NEW_TASK,
	NEW_CHAT_MESSAGE,
	SLA_HALF_TIME_PASSED,
	SLA_OVERDUE,
	CHAT_UNANSWERED_TOO_LONG,
}