ALTER TABLE organization
    ADD COLUMN IF NOT EXISTS active BOOLEAN,
    ADD COLUMN IF NOT EXISTS inn VARCHAR(32),
    ADD COLUMN IF NOT EXISTS kpp VARCHAR(32),
    ADD COLUMN IF NOT EXISTS external_id VARCHAR(128),
    ADD COLUMN IF NOT EXISTS main_address VARCHAR(512),
    ADD COLUMN IF NOT EXISTS priority_level VARCHAR(32),
    ADD COLUMN IF NOT EXISTS manager_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS manager_phone VARCHAR(64),
    ADD COLUMN IF NOT EXISTS manager_email VARCHAR(255),
    ADD COLUMN IF NOT EXISTS contract_number VARCHAR(128),
    ADD COLUMN IF NOT EXISTS contract_start_date DATE,
    ADD COLUMN IF NOT EXISTS contract_end_date DATE,
    ADD COLUMN IF NOT EXISTS tariff_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS service_package_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS monthly_fee NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS description TEXT,
    ADD COLUMN IF NOT EXISTS use_visits_limit BOOLEAN,
    ADD COLUMN IF NOT EXISTS monthly_visits_limit INTEGER,
    ADD COLUMN IF NOT EXISTS visits_used INTEGER,
    ADD COLUMN IF NOT EXISTS extra_visit_price NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS urgent_visit_price NUMERIC(19, 2),
    ADD COLUMN IF NOT EXISTS visit_reset_day INTEGER,
    ADD COLUMN IF NOT EXISTS included_remote_support BOOLEAN,
    ADD COLUMN IF NOT EXISTS visit_comment TEXT,
    ADD COLUMN IF NOT EXISTS sla_agreement_name VARCHAR(255),
    ADD COLUMN IF NOT EXISTS sla_first_response_minutes INTEGER,
    ADD COLUMN IF NOT EXISTS sla_resolution_hours INTEGER,
    ADD COLUMN IF NOT EXISTS sla_work_calendar VARCHAR(64),
    ADD COLUMN IF NOT EXISTS pause_sla_on_waiting_client BOOLEAN,
    ADD COLUMN IF NOT EXISTS sla_comment TEXT,
    ADD COLUMN IF NOT EXISTS service_addresses TEXT,
    ADD COLUMN IF NOT EXISTS communication_channels TEXT,
    ADD COLUMN IF NOT EXISTS internal_comment TEXT;

UPDATE organization
SET
    active = COALESCE(active, TRUE),
    priority_level = COALESCE(priority_level, 'NORMAL'),
    use_visits_limit = COALESCE(use_visits_limit, FALSE),
    monthly_visits_limit = COALESCE(monthly_visits_limit, 0),
    visits_used = COALESCE(visits_used, 0),
    visit_reset_day = COALESCE(visit_reset_day, 1),
    included_remote_support = COALESCE(included_remote_support, TRUE),
    sla_work_calendar = COALESCE(sla_work_calendar, 'GENERAL_SETTINGS'),
    pause_sla_on_waiting_client = COALESCE(pause_sla_on_waiting_client, TRUE);

ALTER TABLE organization
    ALTER COLUMN active SET DEFAULT TRUE,
    ALTER COLUMN active SET NOT NULL,
    ALTER COLUMN priority_level SET DEFAULT 'NORMAL',
    ALTER COLUMN priority_level SET NOT NULL,
    ALTER COLUMN use_visits_limit SET DEFAULT FALSE,
    ALTER COLUMN use_visits_limit SET NOT NULL,
    ALTER COLUMN monthly_visits_limit SET DEFAULT 0,
    ALTER COLUMN monthly_visits_limit SET NOT NULL,
    ALTER COLUMN visits_used SET DEFAULT 0,
    ALTER COLUMN visits_used SET NOT NULL,
    ALTER COLUMN visit_reset_day SET DEFAULT 1,
    ALTER COLUMN visit_reset_day SET NOT NULL,
    ALTER COLUMN included_remote_support SET DEFAULT TRUE,
    ALTER COLUMN included_remote_support SET NOT NULL,
    ALTER COLUMN sla_work_calendar SET DEFAULT 'GENERAL_SETTINGS',
    ALTER COLUMN sla_work_calendar SET NOT NULL,
    ALTER COLUMN pause_sla_on_waiting_client SET DEFAULT TRUE,
    ALTER COLUMN pause_sla_on_waiting_client SET NOT NULL;
