ALTER TABLE user_t
    ADD COLUMN IF NOT EXISTS notify_chat_ping BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS notify_task_chat_ping BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS notify_new_assigned_task BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS notify_task_new_message_assigned BOOLEAN NOT NULL DEFAULT FALSE;