INSERT INTO app_settings (id,
                          timezone,
                          working_time_enabled,
                          workday_start,
                          workday_end,
                          monday_enabled,
                          tuesday_enabled,
                          wednesday_enabled,
                          thursday_enabled,
                          friday_enabled,
                          saturday_enabled,
                          sunday_enabled)
VALUES (1,
        'Europe/Moscow',
        true,
        '09:00',
        '18:00',
        true,
        true,
        true,
        true,
        true,
        false,
        false)
ON CONFLICT (id) DO NOTHING;